services:
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: redis
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'

  web:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - '.:/small_app'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

volumes:
  redis:
  postgres:
