default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER")%>
  password: <%= ENV.fetch("POSTGRES_PASSWORD")%>

development:
  <<: *default
  database: small_app_development

test:
  <<: *default
  database: small_app_test

production:
  <<: *default
  database: small_app_production
  username: small_app
  password: <%= ENV['SMALL_APP_DATABASE_PASSWORD'] %>
